"""remove unique constraint from image_hash

Revision ID: 7916afc9560f
Revises: 4924861ed48c
Create Date: 2026-06-01 08:22:29.279692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7916afc9560f'
down_revision: Union[str, None] = '4924861ed48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_image_hash_key', 'activities', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('activities_image_hash_key', 'activities', ['image_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
